"""
strategies.py
─────────────
Long-only trading strategies for HW2. Each strategy consumes an
indicator-enriched DataFrame (see ``indicators.add_all_indicators``) and returns
a *position* Series in {0, 1}:

    1 -> hold a full long position that day
    0 -> flat (in cash)

Entry / exit rules are asymmetric, so positions are generated by a small state
machine (``_state_machine``): once an entry fires we stay long until an
exit fires. This matches the "Buy when ... / Sell when ..." phrasing in the
assignment.

The backtester (``backtest.py``) is responsible for shifting positions by one
bar to avoid look-ahead, so these functions may reference same-day indicator
values freely.
"""

import numpy as np
import pandas as pd
from pandas import DataFrame, Series


def _state_machine(entry: Series, exit_: Series) -> Series:
    """
    Convert boolean entry/exit signals into a stateful long-only position series.

    Enter (position -> 1) on the first bar where ``entry`` is True while flat.
    Exit (position -> 0) on the first bar where ``exit_`` is True while long.
    If both fire on the same bar, ``exit_`` wins (conservative).
    """
    idx = entry.index
    e = entry.fillna(False).to_numpy(dtype=bool)
    x = exit_.fillna(False).to_numpy(dtype=bool)

    pos = np.zeros(len(idx), dtype=float)
    holding = False
    for i in range(len(idx)):
        if holding:
            if x[i]:
                holding = False
        elif e[i] and not x[i]:
            holding = True
        pos[i] = 1.0 if holding else 0.0
    return pd.Series(pos, index=idx, name="position")


# ── Strategy 1: Trend Following ───────────────────────────────────────────
def trend_following(df: DataFrame, adx_threshold: float = 25.0) -> Series:
    """
    Trend Following (MACD + ADX).

    Buy  when: MACD > Signal AND ADX > adx_threshold  (strong up-trend)
    Sell when: MACD < Signal                          (momentum rolls over)
    """
    entry = (df["macd"] > df["macd_signal"]) & (df["adx"] > adx_threshold)
    exit_ = df["macd"] < df["macd_signal"]
    return _state_machine(entry, exit_)


# ── Strategy 2: Mean Reversion ────────────────────────────────────────────
def mean_reversion(df: DataFrame, rsi_low: float = 30.0, rsi_high: float = 70.0) -> Series:
    """
    Mean Reversion (RSI + Bollinger Bands).

    Buy  when: RSI < rsi_low  AND close < lower Bollinger Band  (oversold)
    Sell when: RSI > rsi_high AND close > upper Bollinger Band  (overbought)
    """
    entry = (df["rsi"] < rsi_low) & (df["close"] < df["bb_lower"])
    exit_ = (df["rsi"] > rsi_high) & (df["close"] > df["bb_upper"])
    return _state_machine(entry, exit_)


# ── Strategy 3: Custom (Trend + Momentum + Volume confirmation) ───────────
def custom(df: DataFrame) -> Series:
    """
    Custom "triple-confirmation" strategy combining three indicator categories:

        Trend    : close above its 50-day SMA
        Momentum : RSI above 50 (bullish momentum)
        Volume   : Chaikin Money Flow > 0 (net buying pressure)

    Buy  when: close > SMA(50) AND RSI > 50 AND CMF > 0
    Sell when: close < SMA(50) OR  RSI < 50

    Requiring three independent categories to agree filters out weak signals;
    exiting on the first sign of trend/momentum breakdown protects gains.
    """
    entry = (df["close"] > df["sma_50"]) & (df["rsi"] > 50) & (df["cmf"] > 0)
    exit_ = (df["close"] < df["sma_50"]) | (df["rsi"] < 50)
    return _state_machine(entry, exit_)


def buy_and_hold(df: DataFrame) -> Series:
    """Benchmark: fully invested for the entire period."""
    return pd.Series(1.0, index=df.index, name="position")


# Registry so the runner/notebook can iterate cleanly.
STRATEGIES = {
    "Buy & Hold": buy_and_hold,
    "Trend Following": trend_following,
    "Mean Reversion": mean_reversion,
    "Custom": custom,
}
